name: homuino
description: "fyp"
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.8.0

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  firebase_core: ^3.13.1
  firebase_auth: ^5.5.4
  google_sign_in: ^6.3.0
  http: ^1.4.0
  wifi_scan: ^0.4.1+2
  connectivity_plus: ^6.1.4
  wifi_iot: ^0.3.19+2
  cloud_firestore: ^5.6.9
  firebase_database: ^11.3.7
  flutter_riverpod: ^2.6.1
  google_fonts: ^6.2.1
  intl: ^0.20.2
  permission_handler: ^12.0.0+1
  network_info_plus: ^6.1.4
  shared_preferences: ^2.5.3
  uuid: ^4.5.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/google_logo.png